name: Open Source Credit Request - DigitalOcean Transfer
description: Request free credits for your open source projects if you were affected by the DigitalOcean open source program shutdown!
title: "[OSCR] "
labels: ["new"]
type: application
body:
  - type: markdown
    attributes:
      value: |
        If you're affected by DigitalOcean shutting down their OSS credits program, apply here.
  - type: input
    id: name
    attributes:
      label: Name of the Project
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Source Link
      description: Please link the source code and/or website.
      placeholder: "- https://terrapkg.com\n- https://github.com/terrapkg/packages"
    validations:
      required: true
  - type: input
    id: usage
    attributes:
      label: Usage
      description: Describe what you were using at DigitalOcean (ex. droplet count, specs, etc.).
    validations:
      required: true
  - type: textarea
    id: more
    attributes:
      label: More
      description: Elaborate on any information you think we should know.
