name: Open Source Credit Request - DigitalOcean Transfer
description: Request free credits for your open source projects if you were affected by the DigitalOcean open source program shutdown!
title: "[OSCR] "
labels: ["new"]
type: application
body:
  - type: markdown
    attributes:
      value: |
        If you're affected by DigitalOcean shutting down their OSS credits program, apply here. If you're accepted, we ask that you add a small badge to your website/README.
  - type: input
    id: name
    attributes:
      label: Name of the Project
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Links
      description: Please link the source code and/or website.
      placeholder: "- https://terrapkg.com\n- https://github.com/terrapkg/packages"
    validations:
      required: true
  - type: input
    id: received
    attributes:
      label: How much did you receive from DigitalOcean?
      placeholder: "ex. $60/year"
    validations:
      required: true
  - type: textarea
    id: usage
    attributes:
      label: Usage
      description: Describe what you were using at DigitalOcean (ex. droplet count, specs, etc.), along with what you used them for.
    validations:
      required: true
  - type: textarea
    id: more
    attributes:
      label: More
      description: Elaborate on any information you think we should know.
  - type: input
    id: email
    attributes:
      label: What email should we use to contact you?
      description: 'If you wish to keep your email private, please write "N/A" and email us your issue link to `oss@fyrastack.com`.'
      placeholder: "you@example.com"
    validations:
      required: false
